
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  user: taskify
  password: rootroot
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: drop_ticket_development


test:
  <<: *default
  database: drop_ticket_test


production:
  primary: &primary_production
    <<: *default
    database: drop_ticket_production
    username: drop_ticket
    password: <%= ENV["DROP_TICKET_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: drop_ticket_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: drop_ticket_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: drop_ticket_production_cable
    migrations_paths: db/cable_migrate
